// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLH-B_lY8M_863znyQ3A8_IDiFbh1vfZ4',
    appId: '1:616518390554:web:1780455ca131e7802752a3',
    messagingSenderId: '616518390554',
    projectId: 'iceicebaby-62b65',
    authDomain: 'iceicebaby-62b65.firebaseapp.com',
    databaseURL: 'https://iceicebaby-62b65-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iceicebaby-62b65.firebasestorage.app',
    measurementId: 'G-29JKCWG2GM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3twh8PLksNDZOhb9bMAhf0tozQ6Qx1SM',
    appId: '1:616518390554:android:2e380dc317a8935e2752a3',
    messagingSenderId: '616518390554',
    projectId: 'iceicebaby-62b65',
    databaseURL: 'https://iceicebaby-62b65-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iceicebaby-62b65.firebasestorage.app',
  );
}
